import React from "react";
import "../styles/projects.css";
import Navbar from "./Navbar";
import { AiFillGithub } from "react-icons/ai";
import { BiWorld } from "react-icons/bi";

const Projects = () => {
  return (
    <>
      <Navbar />
      <div className="projects">
        <h1>Projects Section</h1>
        <p>
          I have been focusing on Front-End Projects since I finished my
          Full-Stack Development Course at Lambda School, here are some of my
          latest projects
        </p>
        <section className="photos">
          <div className="project">
            <img src="photos/cocoscrnshot.webp" alt="cocoloko screenshot" />
            <img
              src="photos/mobileCoco.webp"
              alt="mobile version"
              className="mobile"
            />
            <div className="icons">
              <a
                href="https://github.com/Eric-Santos/cocolokoep"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillGithub size="30" />
              </a>
              <a
                href="https://cocolokoep.com/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <BiWorld size="30" />
              </a>
            </div>
            <h1>Cocolokoep.com</h1>
            <p>
              Coco Loko is a restaurant in El Paso, TX serving seafood. This
              site highlights their menu and was developed using React.js as a
              Progressive Web App, LESS, React Router, and Optimized for Core
              Web Vitals. This person was previously a client of mine, and I was
              happy to help them out with their latest project.
            </p>
          </div>
          <div className="project">
            <img
              src="photos/solarcea.webp"
              alt="clean energy america website"
            />
            <img
              src="photos/mobilecea.webp"
              alt="mobile website"
              className="mobile"
            />
            <div className="icons">
              <a
                href="https://github.com/eric-santosCEA/second-solarcea"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillGithub size="30" />
              </a>
              <a
                href="https://second-solarcea.vercel.app/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <BiWorld size="30" />
              </a>
            </div>
            <h1>Clean Energy America</h1>
            <p>
              Clean Energy America focuses on solar panel installation, roofing
              services, and water filtration as part of its business. This
              website is focused on the solar panel aspect and was created with
              React.js, React Router, Sass, Framer Motion. All the text on this
              site was either written by me or automatically generated by a
              neural network with the help of a program called Copy.ai.
            </p>
          </div>
          <div className="project">
            <img src="photos/portfolio.webp" alt="code background" />
            <div className="icons">
              <a href="https://github.com/Eric-Santos/pwa-portfolio">
                <AiFillGithub size="30" />
              </a>
            </div>
            <h1>Portfolio</h1>
            <p>
              This page is built with React.js, React Hooks, React Router,
              Progressive Web App, Code Splitting, Lazy Loading, and Framer
              Motion. It is optimized for Core Web Vitals with 100% performance,
              Accessibility, Best Practices, and SEO scores.
            </p>
          </div>
        </section>
      </div>
    </>
  );
};

export default Projects;
